### PR TITLE
feat: show breadcrumbs in search results

### PR DESCRIPTION
**Pull request by Gr3q**
* Resolve https://github.com/imfing/hextra/issues/469

Shows breadcrumbs instead of the page title for each section of the search results.

For some reason `data` can be incomplete on [our site](https://github.com/netduma/knowledge-base), I need to figure out why exactly.

### CODE REVIEW

**Comment by imfing** [comment]
> For some reason data can be incomplete on [our site](https://github.com/netduma/knowledge-base), I need to figure out why exactly.

might be caused by the parsing logic, i suggest you take a look at: https://github.com/imfing/hextra/blob/main/layouts/partials/utils/fragments.html

**Comment by Gr3q** [comment]
I had a look, it's this line: https://github.com/imfing/hextra/blob/97ea67198b2f5439b5ba727e831ea4f7d30a0df2/assets/json/search-data.json#L10

It excludes pages from search with no content. There are 2 options:
* Empty pages should not be excluded from search (can still be explicitly excluded with `excludeSearch`)
* Should just warn in console (like now in the PR) for both excluded/empty content pages that have children.

To be honest pages that have children should not be excluded with `excludeSearch` nor they should be empty most of the time.

It's up to you which option you choose for this PR - for our page I'll have to add content for the relevant pages (as they should have content)

**Comment by imfing** [comment]
@Gr3q thanks the PR overall makes sense to me. 

re: page exclusion that you mentioned

> It excludes pages from search with no content. 

I kinda forget what was the reason to put that line to exclude page without content. Maybe we could remove that line since we have `excludeSearch`?

**Comment by Gr3q** [comment]
> I kinda forget what was the reason to put that line to exclude page without content. Maybe we could remove that line since we have excludeSearch?

Can do, I checked before and it doesn't seem to break search in any way, and you can search for the title of empty pages.

**Review by imfing — APPROVED** [review]
looks good, thanks!

**Pull request merged**
