### PR TITLE
chore(style): better footer logo alignment

### PR DESCRIPTION
**Pull request by c2tz**
I just added a -2.5px value for the footer logo because the base logo tended to be a little too low and not aligned with the "Hextra". Not sure it's very useful, but here it is anyway. On the left, the modified version, and on the right, the basic version.

chrome_myg9wuGcJo

### CODE REVIEW

**Review by imfing — CHANGES_REQUESTED** [review]
Thanks for the PR! It looks like you're editing the auto-compiled CSS. For styling changes, please use [Tailwind CSS classes](https://tailwindcss.com/docs/utility-first) as outlined in our [Contributing Guide](https://github.com/imfing/hextra/blob/main/.github/CONTRIBUTING.md#compile-the-styles).

**Comment by c2tz** [comment]
ok sorry it's better ?

**Comment by c2tz** [comment]
wait i enlarged too much the svg icon i thought i did well because it would have lost me an alignment but it overflows because it is more than 14px

**Comment by c2tz** [comment]
ok for me 

chrome_9iX0q7Gtzc

**Comment by imfing** [comment]
@c2tz thanks, that should be it, the change looks good to me 👍

**Review by imfing — APPROVED** [review]

**Pull request merged**
