### PR TITLE
feat: update mermaid version

### PR DESCRIPTION
**Pull request by PurpleBabar**
The title is self explanatory ;) Since the version 11 supports new types of diagram it would be cool to support version 11 of mermaid js :)

### CODE REVIEW

**Review by imfing — CHANGES_REQUESTED** [review]
Would you mind run this `task libs` which fetches the newest Mermaid lib files?

**Comment by PurpleBabar** [comment]
Will do :) I thought this was done automatically in build with github action :)

**Comment by PurpleBabar** [comment]
Done :)

**Review by imfing — APPROVED** [review]

**Comment by imfing** [comment]
thank you @PurpleBabar

**Comment by mmurdockk** [comment]
Thank you @PurpleBabar, upgrading hextra to 0.8.6 allowed me to fix all my mermaid diagrams and that's awesome :p

**Pull request merged**
